### ISSUE TITLE
Extrinsics (lidar -> IMU)

### ISSUE THREAD

**Issue by tigerschweiger** [IPNL-POLYU/UrbanNavDataset#1]
################## Extrinsic parameter from Center Lidar to IMU##################
CENTER_LiDAR_T_IMU: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 1, 0, 0, 0,
           0, 1, 0, 0,
           0, 0, 1, 0.28, 
           0, 0, 0, 1]
I test the data with LIO-SAM, which yaml needs extrinsicRot and extrinsicRPY
From the extrinsic.yaml above the data represents "extrinsicRot" right? If yes, what is the extrinsicRPY, is it an identify matrix?

**Comment by DarrenWong** [comment]
The image is a little blur. Assume you are using Evo and using the default frame in LIOSAM, you can use --align to make it match.

But the root reason is the LIOSAM uses IMU orientation to rotate the coordinate for better alignment with GNSS ( it would be easy to check if you pay attention to the initial state).

https://github.com/TixiaoShan/LIO-SAM/blob/3a3d82fac4ba614ff2324be4ef83381b4256cc48/include/utility.h#L263

If you are not using GPS, you can directly set **q_from** as identity matrix should be aligned well in the LiDAR frame
`        Eigen::Quaterniond q_from(1,0, 0, 0);`

**Comment by tigerschweiger** [comment]
> The image is a little blur. Assume you are using Evo and using the default frame in LIOSAM, you can use --align to make it match.
> 
> But the root reason is the LIOSAM uses IMU orientation to rotate the coordinate for better alignment with GNSS ( it would be easy to check if you pay attention to the initial state).
> 
> https://github.com/TixiaoShan/LIO-SAM/blob/3a3d82fac4ba614ff2324be4ef83381b4256cc48/include/utility.h#L263
> 
> If you are not using GPS, you can directly set **q_from** as identity matrix should be aligned well in the LiDAR frame ` Eigen::Quaterniond q_from(1,0, 0, 0);`

Thanks! I solved this problem using add "--align", yeah it was Evo method.
