### ISSUE TITLE
IMU classification

### ISSUE THREAD

**Issue by paaraujo** [IPNL-POLYU/UrbanNavDataset#13]
Would you classify the Xsens MTI 10 series used in HK as a low-cost IMU?

*This is not an issue, it is more a question. Inside Github we can have a [discussion page](https://docs.github.com/en/discussions). It would be nice to have a space like that within the dataset.

**Comment by DarrenWong** [comment]
In my opinion, it quite depends on the application.
For autonomous driving, the Xsens MTI 10 series is not expensive compared to the high-end IMU with low bias. And the hardware price would be lower if the quantity goes up.

For smartphone usage, it would be very expensive 😀

**Comment by paaraujo** [comment]
Thanks for your insight Darren! I agree with you :smile:
