### ISSUE TITLE
Span + IE + Rosbag

### ISSUE THREAD

**Issue by paaraujo** [IPNL-POLYU/UrbanNavDataset#14]
How did you include the processed reference in the rosbag?

**Comment by DarrenWong** [comment]
You can use the ROS API to do so. http://wiki.ros.org/rosbag/Code%20API

**Comment by paaraujo** [comment]
Hi @DarrenWong, that is interesting. Doesn't it mess with the timestamps? Do you record the bag during the experiment and add the reference later?

**Comment by DarrenWong** [comment]
Yes, we post-processing the ground truth with IE then add it into rosbag. As the reference point has a UTC timestamp, you can assign the timestamp to the message with some code like this,

`bag.write("/novatel_data/inspvax", gt_utc, latest_gt);`

**Comment by paaraujo** [comment]
Do you record the reference data using the NovAtel software suite?

**Comment by DarrenWong** [comment]
Yes, we need to post-processing the data. You can also use the [Novatel ROS driver](https://github.com/ros-drivers/novatel_span_driver) directly if the real-time output is needed.

**Comment by paaraujo** [comment]
Thanks @DarrenWong!
