### ISSUE TITLE
mapping with urbannav-hk-medium-urban-1

### ISSUE THREAD

**Issue by Kailthen** [IPNL-POLYU/UrbanNavDataset#19]
使用urbannav-hk-medium-urban-1数据的/velodyne_points做点云建图，效果如下，有些明显异常的点，还不清楚是如何产生的
![image](https://user-images.githubusercontent.com/46671312/182507425-5c5c4d6a-3900-4d51-9fea-20191e2b7374.png)
![image](https://user-images.githubusercontent.com/46671312/182507665-0577f241-377c-4714-83bd-6b8e0032b283.png)
有谁碰到类似问题吗

**Comment by DarrenWong** [comment]
你好，这个是由于激光雷达原始点云采集的一些噪声，你可以通过一个简单的filter 例如过滤z超过负5米，或者用pcl的StatisticalOutlierRemoval 也可以过滤。

**Comment by Kailthen** [comment]
明白，感谢~
