### ISSUE TITLE
About the value z of UrbanNav-HK-Medium-Urban-1 dataset

### ISSUE THREAD

**Issue by fentuoli** [IPNL-POLYU/UrbanNavDataset#21]
![Screenshot 2022-09-05 16:49:55](https://user-images.githubusercontent.com/36686362/188409810-b28de1fa-d2b9-4a32-b125-b6eda5c49fd6.png)
Hi, I'm sorry to bother you. I found that  as the vehicle moves, the height of the point scanned by the laser gradually becomes negative.
The picture above is a few frames I took after the bag played for a while, the red point in the picture represent the pose of the current laser, and I set z to 0.
I don't understand why the heights of the scanned points are all negative. Maybe this question is naive, but it really confuses me and prevents me from capturing point clouds with a fixed height range.
Hoping to your reply. Thanks a lot!

**Comment by fentuoli** [comment]
Sorry, I found out that it was something wrong with my point cloud transformation function that caused the z of the original points to change, I'm so sorry to bother you!

**Comment by DarrenWong** [comment]
Glad to see you solved your problem! the RVIZ indicates that the points have a positive height which scanned the buildings, as shown in the figure below,

![1662369616179](https://user-images.githubusercontent.com/5771106/188415231-3ab8974f-5e27-403d-aac8-205daeb0d799.png)

**Comment by fentuoli** [comment]
> Glad to see you solved your problem! the RVIZ indicates that the points have a positive height which scanned the buildings, as shown in the figure below,
> 
> ![1662369616179](https://user-images.githubusercontent.com/5771106/188415231-3ab8974f-5e27-403d-aac8-205daeb0d799.png)

I'll have a check! Thanks a lot!
