### ISSUE TITLE
点云地图

### ISSUE THREAD

**Issue by ZhaoXiaoyu01** [IPNL-POLYU/UrbanNavDataset#23]
您好，想请教下您给出的点云地图是如何得到的呢？是通过真值轨迹拼接的吗？

**Comment by DarrenWong** [comment]
对的，目前点云地图是通过真值拼接的。我们也在尝试采用图优化的方法把真值和LiDAR融合在解决一些场景真值不准的场景。

**Comment by ZhaoXiaoyu01** [comment]
谢谢您的解答，想另外问一下我们的真值数据是3轴的还是6轴的，为什么我通过下面代码中的方式结算的姿态是有问题的，是我的方式不对吗？
`    void parse(novatel_msgs::INSPVAXConstPtr msg) {
        Eigen::AngleAxisd rollAngle(msg->roll, Eigen::Vector3d::UnitX());
        Eigen::AngleAxisd pitchAngle(msg->pitch, Eigen::Vector3d::UnitY());
        Eigen::AngleAxisd yawAngle(msg->azimuth, Eigen::Vector3d::UnitZ());
        Eigen::Quaterniond q = yawAngle*pitchAngle*rollAngle;
    }`

**Comment by DarrenWong** [comment]
Novatel 给出的真值跟ROS里面定义有点不一致， roll, pitch和azimuth的定义可见:
https://hexagondownloads.blob.core.windows.net/public/Novatel/assets/Documents/Bulletins/apn037/apn037.pdf

你也可以通过python脚本把novatel转成local frame (LiDAR/IMU)
https://github.com/IPNL-POLYU/UrbanNavDataset/tree/master/tools/gt_vis

**Comment by ZhaoXiaoyu01** [comment]
十分感谢
