### ISSUE TITLE
The Gt of UrbanNav-HK-Harsh-Urban

### ISSUE THREAD

**Issue by fentuoli** [IPNL-POLYU/UrbanNavDataset#28]
Dear author,
       I found the start timestamp of gt of harsh-urban dataset you provided is 1621307670, but in the UrbanNav-HK_Mongkok-20210518_sensors.bag, the topic "/velodyne_points/header" shows the start timestamp is 1621307217. It means I should play the bag from a fixed timestamp?

Best Wishes!

**Comment by DarrenWong** [comment]
If you want to evaluate LiDAR with GT, you need to play from a fixed timestamp, as only part of the GT is verified. For more details, you can refer to this issue https://github.com/IPNL-POLYU/UrbanNavDataset/issues/12
