### ISSUE TITLE
Tunnel Dataset crashed

### ISSUE THREAD

**Issue by tigerschweiger** [IPNL-POLYU/UrbanNavDataset#3]
I ran the UrbanNav-HK-Tunnel-1 with LIO-SAM, which was no doubt crashed because of less structure features
![2021-10-19 17-05-36 的屏幕截图](https://user-images.githubusercontent.com/61806268/137940158-4a391b87-9bbd-4246-b487-c7414bb8f8eb.png)
I tried it again with LVI-SAM, which fused Visual-Odometry, but it also crashed
![2021-10-19 17-06-06 的屏幕截图](https://user-images.githubusercontent.com/61806268/137940409-9f6253e2-cd5a-4f61-a2e1-05151cfb279a.png)
I wondered if there were any good methods to deal with this scenes?

**Comment by yinhaosen** [comment]
I am confused about if the above parameters are LIO-SAM's or LVI-SAM's because it seems like LIO-SAM but the project name shows LVI-SAM. I tested on LIO-SAM. It really drifted and crashed from the very beginning.

**Comment by DarrenWong** [comment]
Yes, the performance of LiDAR slam is very challenging in tunnel data. For the evaluation of the tunnel, you can refer to Fig.11 of the paper "A Review of Multi-Sensor Fusion SLAM Systems Based on 3D LIDAR" https://www.mdpi.com/2072-4292/14/12/2835
