### ISSUE TITLE
About reference conversion

### ISSUE THREAD

**Issue by nothing371442** [IPNL-POLYU/UrbanNavDataset#31]
In [UrbanNavDataset](https://github.com/IPNL-POLYU/UrbanNavDataset)/[tools](https://github.com/IPNL-POLYU/UrbanNavDataset/tree/master/tools)/[gt_vis](https://github.com/IPNL-POLYU/UrbanNavDataset/tree/master/tools/gt_vis)/convert_novatel_to_pose.py,
I found it do operation as yaw = np.deg2rad(-1.0 * azimuth), which I am confused about.
I found that azimuth is Eular angle for NED, for it represents the angle between vehicle driving and the North. The yaw in ENU may be defined as the angle between vehicle driving and the East. So, I think it may be yaw = np.deg2rad(90-1.0 * azimuth) to do ENU transformer. I don't know why and look forwards for any suggestions or help.

**Comment by nothing371442** [comment]
I also test the velocity in reference.csv, and I found it may be velocity in ENU frame, not in body frame.

**Comment by DarrenWong** [comment]
> In [UrbanNavDataset](https://github.com/IPNL-POLYU/UrbanNavDataset)/[tools](https://github.com/IPNL-POLYU/UrbanNavDataset/tree/master/tools)/[gt_vis](https://github.com/IPNL-POLYU/UrbanNavDataset/tree/master/tools/gt_vis)/convert_novatel_to_pose.py, I found it do operation as yaw = np.deg2rad(-1.0 * azimuth), which I am confused about. I found that azimuth is Eular angle for NED, for it represents the angle between vehicle driving and the North. The yaw in ENU may be defined as the angle between vehicle driving and the East. So, I think it may be yaw = np.deg2rad(90-1.0 * azimuth) to do ENU transformer. I don't know why and look forwards for any suggestions or help.

Yes you are right if you need to transform yaw to ENU with **yaw = np.deg2rad(90-1.0 * azimuth)** . The yaw in the convert_novatel_to_pose.py is a middle variable for the transformation only. 
https://github.com/IPNL-POLYU/UrbanNavDataset/blob/73596f3fbe45b24bfd22b9e5b952e27d2ec84c43/tools/gt_vis/convert_novatel_to_pose.py#L27

We apply the transformation and output the angle as rotation matrix/quaternion according to [here](https://hexagondownloads.blob.core.windows.net/public/Novatel/assets/Documents/Bulletins/apn037/apn037.pdf)

https://github.com/IPNL-POLYU/UrbanNavDataset/blob/73596f3fbe45b24bfd22b9e5b952e27d2ec84c43/tools/gt_vis/convert_novatel_to_pose.py#L37

**Comment by nothing371442** [comment]
> > In [UrbanNavDataset](https://github.com/IPNL-POLYU/UrbanNavDataset)/[tools](https://github.com/IPNL-POLYU/UrbanNavDataset/tree/master/tools)/[gt_vis](https://github.com/IPNL-POLYU/UrbanNavDataset/tree/master/tools/gt_vis)/convert_novatel_to_pose.py, I found it do operation as yaw = np.deg2rad(-1.0 * azimuth), which I am confused about. I found that azimuth is Eular angle for NED, for it represents the angle between vehicle driving and the North. The yaw in ENU may be defined as the angle between vehicle driving and the East. So, I think it may be yaw = np.deg2rad(90-1.0 * azimuth) to do ENU transformer. I don't know why and look forwards for any suggestions or help.
> 
> Yes you are right if you need to transform yaw to ENU with **yaw = np.deg2rad(90-1.0 * azimuth)** . The yaw in the convert_novatel_to_pose.py is a middle variable for the transformation only.
> 
> https://github.com/IPNL-POLYU/UrbanNavDataset/blob/73596f3fbe45b24bfd22b9e5b952e27d2ec84c43/tools/gt_vis/convert_novatel_to_pose.py#L27
> 
> We apply the transformation and output the angle as rotation matrix/quaternion according to [here](https://hexagondownloads.blob.core.windows.net/public/Novatel/assets/Documents/Bulletins/apn037/apn037.pdf)
> 
> https://github.com/IPNL-POLYU/UrbanNavDataset/blob/73596f3fbe45b24bfd22b9e5b952e27d2ec84c43/tools/gt_vis/convert_novatel_to_pose.py#L37

Thanks~ But I notice that in https://hexagondownloads.blob.core.windows.net/public/Novatel/assets/Documents/Bulletins/apn037/apn037.pdf, it said it is needed to convert azimuth to yaw to form 
the matrix. I am wondering why the middle variable is yaw = np.deg2rad(-1.0 * azimuth) rather than yaw = np.deg2rad(90 - 1.0 * azimuth). Because the rotation matrix is typically used to transform right-front-up the ENU.

**Comment by DarrenWong** [comment]
> I also test the velocity in reference.csv, and I found it may be velocity in ENU frame, not in body frame.

For your second question, do you mean the velocity in the 0428 data? The header says in the ENU frame. But the rest data, including deep urban, harsh urban etc ,  are represented in the body frame.
Data in 0428
![image](https://user-images.githubusercontent.com/5771106/204467847-413dc270-809e-4888-b8c2-e5d9edf46e81.png)

Data in the GT
![image](https://user-images.githubusercontent.com/5771106/204469178-d5663754-3bd9-4c07-98e9-d5e74ca92f92.png)

**Comment by nothing371442** [comment]
> > I also test the velocity in reference.csv, and I found it may be velocity in ENU frame, not in body frame.
> 
> For your second question, do you mean the velocity in the 0428 data? The header says in the ENU frame. But the rest data, including deep urban, harsh urban etc , are represented in the body frame. Data in 0428 ![image](https://user-images.githubusercontent.com/5771106/204467847-413dc270-809e-4888-b8c2-e5d9edf46e81.png)
> 
> Data in the GT ![image](https://user-images.githubusercontent.com/5771106/204469178-d5663754-3bd9-4c07-98e9-d5e74ca92f92.png)

Thanks for your detailed answers, which is very helpful. ^^

**Comment by DarrenWong** [comment]
> > > In [UrbanNavDataset](https://github.com/IPNL-POLYU/UrbanNavDataset)/[tools](https://github.com/IPNL-POLYU/UrbanNavDataset/tree/master/tools)/[gt_vis](https://github.com/IPNL-POLYU/UrbanNavDataset/tree/master/tools/gt_vis)/convert_novatel_to_pose.py, I found it do operation as yaw = np.deg2rad(-1.0 * azimuth), which I am confused about. I found that azimuth is Eular angle for NED, for it represents the angle between vehicle driving and the North. The yaw in ENU may be defined as the angle between vehicle driving and the East. So, I think it may be yaw = np.deg2rad(90-1.0 * azimuth) to do ENU transformer. I don't know why and look forwards for any suggestions or help.
> > 
> > 
> > Yes you are right if you need to transform yaw to ENU with **yaw = np.deg2rad(90-1.0 * azimuth)** . The yaw in the convert_novatel_to_pose.py is a middle variable for the transformation only.
> > https://github.com/IPNL-POLYU/UrbanNavDataset/blob/73596f3fbe45b24bfd22b9e5b952e27d2ec84c43/tools/gt_vis/convert_novatel_to_pose.py#L27
> > 
> > We apply the transformation and output the angle as rotation matrix/quaternion according to [here](https://hexagondownloads.blob.core.windows.net/public/Novatel/assets/Documents/Bulletins/apn037/apn037.pdf)
> > https://github.com/IPNL-POLYU/UrbanNavDataset/blob/73596f3fbe45b24bfd22b9e5b952e27d2ec84c43/tools/gt_vis/convert_novatel_to_pose.py#L37
> 
> Thanks~ But I notice that in https://hexagondownloads.blob.core.windows.net/public/Novatel/assets/Documents/Bulletins/apn037/apn037.pdf, it said it is needed to convert azimuth to yaw to form the matrix. I am wondering why the middle variable is yaw = np.deg2rad(-1.0 * azimuth) rather than yaw = np.deg2rad(90 - 1.0 * azimuth). Because the rotation matrix is typically used to transform right-front-up to the ENU.

Sorry for some mistakes in my previous reply. Actually the azimuth = 0 when the vehicle heading north (the azimuth is around y axis, clock-wise), which equals to ENU yaw=0. Therefore, 90 degrees is not necessary.

Page 26 of SPAN CPT manual
![image](https://user-images.githubusercontent.com/5771106/204475549-55e68730-13c4-4dd0-9081-318c2297af6b.png)

span cpt manual: https://hexagondownloads.blob.core.windows.net/public/Novatel/assets/Documents/Manuals/om-20000122/om-20000122.pdf

**Comment by nothing371442** [comment]
> Actually the azimuth = 0 when the vehicle heading north (the azimuth is around y axis, clock-wise), which equals to ENU yaw=0.

I am sorry that, when the azimuth = 0 represents the vehicle heading north (the azimuth is around y axis, clock-wise). Is it equals to ENU yaw=90, and NED yaw = 0 ?

**Comment by DarrenWong** [comment]
Do you mean the ENU yaw=90, which x-axis heading north?  I am not very familiar with NED. But it seems to be a transformation rather than only yaw conversion, depending on your definition.

![image](https://user-images.githubusercontent.com/5771106/204483564-cc10356c-98d6-401c-be7d-a6ed7d93981c.png)

**Comment by nothing371442** [comment]
> Do you mean the ENU yaw=90, which x-axis heading north? I am not very familiar with NED. But it seems to be a transformation rather than only yaw conversion, depending on your definition.
> 
> ![image](https://user-images.githubusercontent.com/5771106/204483564-cc10356c-98d6-401c-be7d-a6ed7d93981c.png)

I mean when y-axis (vehicle-front direction) heading north, in this situation, ENU yaw=90, at the same time NED yaw=0. For ENU yaw, it may represent the angle between vehicle-front direction and the East. For NED yaw, it may represent the angle between vehicle-front direction and the North.  I think maybe the middle variable "yaw" can use ENU yaw to do transformation.

**Comment by DarrenWong** [comment]
Yes yes, you can try to do some.

**Comment by nothing371442** [comment]
> Yes yes, you can try to do some.

Thanks a lot, Darren. ^^
