### ISSUE TITLE
传感器标定

### ISSUE THREAD

**Issue by gkychd** [IPNL-POLYU/UrbanNavDataset#36]
你好，请问一下各个传感器都是通过什么方法进行标定的，时间同步问题怎么解决

**Comment by ZARDheart** [comment]
感觉更新的几个数据的相机与IMU之间标定参数似乎不太对

**Comment by DarrenWong** [comment]
感谢对我们的工作的关注，

标定部分: 
IMU部分我们采用Allan Variance ( https://github.com/gaowenliang/imu_utils)
视觉部分: 采用CAD的设计参数+Kalibr,
LiDAR部分: 采用CAD设计参数+ [优化方法](https://github.com/APRIL-ZJU/lidar_IMU_calib)标定
GNSS接收机: 采用CAD设计参数+人工标定

时间同步: 我们采用Chrony + GPSd 来接收Ublox M8T NMEA+PPS 信号去同步ROS工控机到GPS时间，每个传感器均以ROS时间戳为准， 此数据集暂没考虑信号传输的延迟.会继续优化，谢谢~

**Comment by DarrenWong** [comment]
> 
关于相机和IMU部分的，请参考 issue #17  and #27
