### ISSUE TITLE
IMU/GNSS to ground truth extrinsics

### ISSUE THREAD

**Issue by DanieleMarchisotti** [IPNL-POLYU/UrbanNavDataset#37]
I could not find extrinsics between IMU and ground truth.
They would be very helpful to make a comparison between the estimated trajectory and the ground truth one.
Could you provide this information or is it available somewhere?

Thank you!

**Comment by DarrenWong** [comment]
Please refer to https://github.com/IPNL-POLYU/UrbanNavDataset/blob/73596f3fbe45b24bfd22b9e5b952e27d2ec84c43/UrbanNav-HK-Medium-Urban-1/extrinsic.yaml#L73

**Comment by DanieleMarchisotti** [comment]
Thank you very much for your answer!

I have another question. Which is the GNSS receiver that I should use in your dataset?
Because in the extrinsics there is only one transformation matrix between GNSS and IMU (ANTENNA_T_IMU).
Which is the GNSS receiver I should refer to in order to use that extrinsic matrix?

**Comment by DanieleMarchisotti** [comment]
Thank you very much for your answer!

One last question. The IMU data file contains also orientation data (field.orientation.x, field.orientation.y, field.orientation.z, field.orientation.w).
Is it the orientation computed directly from data obtained from IMU by considering only the magnetometer?
If not, does the dataset contains magnetomer measurements?

**Comment by DarrenWong** [comment]
Yes, we are using a Mti 10 AHRS sensor using 3-axis magnetometers.. For more details, you can refer to https://base.xsens.com/s/article/Magnetic-immunity-of-the-MTi-AHRS-1605869708053?language=en_US.

**Comment by DanieleMarchisotti** [comment]
Thank you for your answers.

I have seen that in the IMU csv files there is the covariance matrix for accelerometer, gyroscope and magnetometer.
However, noise models are present also in the file xsense_imu_param.yaml.
Which is the difference between the two noise models?
Which one should I use?

**Comment by DarrenWong** [comment]
Plese use the xsens_imu_param for the noise term. 
The covariance matrix in the IMU files is a constant variance within the data collection according to [here](https://github.com/IPNL-POLYU/ethzasl_xsens_driver/blob/b2070193e446bc3c2563e487206877247c26a3e3/nodes/mtnode.py#L96)
