### ISSUE TITLE
pseudo-distance was much larger than the real distance

### ISSUE THREAD

**Issue by KitKator** [IPNL-POLYU/UrbanNavDataset#38]
I used the gnss-deep data set in Hong Kong and found that the pseudo-distance was much larger than the real distance, in which the pseudo-distance had been processed by satellite ephemeris error and ionospheric tropospheric error. The real distance was the distance from the satellite to the receiver, and the real position and obs observation files you provided were used. May I ask whether there is a deviation of about 0.005s in the time unification of obs file?
I used 20210521.medium-urban.whampoa.ublox.f9p.obs and UrbanNav_whampoa_raw.txt

**Comment by ivannhf** [comment]
Thank you for using the dataset. 
Have the satellite and receiver clock offsets been compensated during the evaluation of the pseudorange observation?

**Comment by KitKator** [comment]
The receiver clock error has been eliminated, thank you very much for your help

**Comment by DarrenWong** [comment]
closed as fixed
