### ISSUE TITLE
Time Synchronization between LiDAR and Ground truth

### ISSUE THREAD

**Issue by YibinWu** [IPNL-POLYU/UrbanNavDataset#39]
Hi, I found that the ground truth data in the dataset has both ROS time and GNSS time, while LiDAR data only has ROS time. How can I align the LiDAR data with the GNSS time? An obvious time drift can be observed if I compare my LiDAR SLAM heading with the Ground truth heading according to the ROS time. Thanks.

**Comment by DarrenWong** [comment]
Thanks for your interest in our work.

Can I know which data are you using? And how do you compare your LiDAR SLAM heading with ground truth? Using evo?

**Comment by DarrenWong** [comment]
Per discussed in email, the 0428 is not time sync. Suggest use the medium urban data instead
