### ISSUE TITLE
how to download bag file?

### ISSUE THREAD

**Issue by chg0901** [IPNL-POLYU/UrbanNavDataset#40]
could you please show me how to download bag file?

in this file(**https://github.com/IPNL-POLYU/UrbanNavDataset/blob/master/docs/GETTING_STARTED.md#visual-inertial-odometry-video**),  

> Data preparation,
> 
> Download the bag file;
> Clone the [VINS-Fusion](https://github.com/HKUST-Aerial-Robotics/VINS-Fusion) repository from GitHub;
> Update camera intrinsics and extrinsics in the yaml file;
> Run the framework of VINS-Fusion:

**Comment by DarrenWong** [comment]
You can refer to the dataset session in the readme.
https://github.com/IPNL-POLYU/UrbanNavDataset#datasets
