### ISSUE TITLE
Confusion about the direction of angles

### ISSUE THREAD

**Issue by NeF51** [IPNL-POLYU/UrbanNavDataset#43]
Dear authors,
  Thank you for your work. Recently, I am working on IMU dead reckong with dataset 20190428 imu.csv and reference.csv. And I have some questions about the direction of the angular rate and angle in these files.
  Which type of direction of angular rate and heading angle in the following picture is correct in imu.csv and reference.csv? The heading angle increases when the vehicle turning anticlockwise or clockwise? Is the forward direction of angular rate of Z axis correct (anticlockwise)?
  Using the direction as the right picture illustrates, the results seems much more reasonable. But it is different from traditional definition in ENU frame.
![微信图片_20230423174006](https://user-images.githubusercontent.com/102210933/233832167-0476f019-f7d9-4ea1-8fbd-c7780ca27975.jpg)

**Comment by DarrenWong** [comment]
Yes, the direction is the same as your right picture illustration. 
 The heading angle in _reference.csv_ increases when the vehicle turns clockwise according to the ground truth positioning provided by the [Novatel Azimuth](https://docs.novatel.com/OEM7/Content/SPAN_Logs/INSPVAX.htm)
The starting point heading in _reference.csv_ is 228 degrees as shown below
![1682295129002](https://user-images.githubusercontent.com/5771106/233874498-881eabd5-5349-4e3b-9497-5ef781797c5d.png)



The forward direction of the angular rate of Z axis in the _imu.csv_ is anticlockwise following the standard [ROS frame](https://www.ros.org/reps/rep-0145.html).  All the frame is right-handed.

**Comment by NeF51** [comment]
> Yes, the direction is the same as your right picture illustration. The heading angle in _reference.csv_ increases when the vehicle turns clockwise according to the ground truth positioning provided by the [Novatel Azimuth](https://docs.novatel.com/OEM7/Content/SPAN_Logs/INSPVAX.htm) The starting point heading in _reference.csv_ is 228 degrees as shown below ![1682295129002](https://user-images.githubusercontent.com/5771106/233874498-881eabd5-5349-4e3b-9497-5ef781797c5d.png)
> 
> The forward direction of the angular rate of Z axis in the _imu.csv_ is anticlockwise following the standard [ROS frame](https://www.ros.org/reps/rep-0145.html). All the frame is right-handed.

Thanks!
