### ISSUE TITLE
Tunnel Dataset issue

### ISSUE THREAD

**Issue by jcmayoral** [IPNL-POLYU/UrbanNavDataset#44]
I have tried to download the dataset with the tunnel. However, once downloaded the bag has some issues and, asked to be reindexed. After, it just shows the initial 54 seconds of the video and stops once the vehicle starts entering the tunnel. Am I doing something wrong?
![Screenshot from 2023-06-22 23-45-13](https://github.com/IPNL-POLYU/UrbanNavDataset/assets/14136339/83670fcf-95da-4278-9d2d-9866edbea919)

**Comment by DarrenWong** [comment]
Hi, I think you didn't download the whole rosbag as you rosbag only 2GB and reindex is required. The whole rosbag should be around 16.8GB


![image](https://github.com/IPNL-POLYU/UrbanNavDataset/assets/5771106/2bffb8e0-29ab-4c84-a8ad-47218d7ecd6a)

![image](https://github.com/IPNL-POLYU/UrbanNavDataset/assets/5771106/c86d5738-e5d3-405f-8bcb-a49fb6eefefd)

**Comment by jcmayoral** [comment]
It is weird. Because before I reindex its 16.8GB and the reindexed bag is 2gb.

**Comment by DarrenWong** [comment]
closed as no further updates
