### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by aang-whu** [IPNL-POLYU/UrbanNavDataset#45]
请问这个开源的东京数据，IMU的安装角和杆臂有详细说明吗

**Comment by DarrenWong** [comment]
感谢对我们的工作的关注，东京数据的外参目前是没有的，已经在readme里面有[注明](https://github.com/IPNL-POLYU/UrbanNavDataset#important-notes-the-lidar-calibration-file-for-the-lidar-sensor-extrinsic-parameters-between-sensors-are-not-available-now-if-you-wish-to-study-the-gnsslidarimu-integration-we-suggest-using-the-dataset-above-collected-in-hong-kong-however-the-gnss-dataset-from-tokyo-is-challenging-which-is-collected-in-challenging-urban-canyons)了
