### ISSUE TITLE
Installation parameters of radar

### ISSUE THREAD

**Issue by WuJing-coder** [IPNL-POLYU/UrbanNavDataset#46]
Hello, I want to know the installation height of 3D lidar in UrbanNav-HK-Medium-Urban-1 data set, thank you.

**Comment by DarrenWong** [comment]
hi you can refer to this link https://github.com/IPNL-POLYU/UrbanNavDataset/blob/master/UrbanNav-HK-Medium-Urban-1/extrinsic.yaml
