### ISSUE TITLE
GNSS基站数据

### ISSUE THREAD

**Issue by Lchhehehe** [IPNL-POLYU/UrbanNavDataset#47]
老师您好，请问harsh、deep、dedium、tunnel等数据集是否有基站的数据，还是说我直接下载附近的参考站的数据就可以？

**Comment by DarrenWong** [comment]
你好，请直接下载香港这边的基站信息即可，离我们比较近的一个叫做HKSC的站点，https://www.geodetic.gov.hk/en/rinex/downv.aspx
