### ISSUE TITLE
ORBSLAM3

### ISSUE THREAD

**Issue by tigerschweiger** [IPNL-POLYU/UrbanNavDataset#5]
Hi! I ran the UrbanNav-HK-Tunnel-1 dataset using the ORBSLAM3 algorithm for the stereo image version. So the trajectory was like that.
![2021-12-10 22-57-56 的屏幕截图](https://user-images.githubusercontent.com/61806268/145646857-dc199f7a-2dc2-4c13-bd13-8791469a3177.png)

I wondered there might be some errors like:
1)In the yaml file of ORBSLAM3 there are only one camera parameter but for the data there are left and right images, so which one i should choose?
2)are there any the Stereo Rectification matrix, which are also in yaml file in ORBSLAM3, such as LEFT.D and LEFT.K and LEFT.R?

**Comment by DarrenWong** [comment]
Hey @tigerschweiger Thank you interest in our work. We do not test the UrbanNav in ORBSLAM3.

The tunnel data in the UrbanNav is a challenging scenario for SLAM. We suggest you can test some other dataset (for example, the [deep urban](https://github.com/IPNL-POLYU/UrbanNavDataset#urbannav-hk-deep-urban-1) which starts in the clear area) to detriment if the YAML file or the limitation of the algorithm before testing the tunnel dataset.
