### ISSUE TITLE
About UrbanLoco groundtruth

### ISSUE THREAD

**Issue by Milalaa** [IPNL-POLYU/UrbanNavDataset#52]
感谢您的分享！
在使用您另一数据集urbanloco有一些问题，该如何得到groundtruth进行evo评估呢？

使用`rostopic echo -b $YOUR_BACK_FILENAME  -p /novatel_data/inspvax > ground_truth.csv `得到了 /novatel_data/inspvax的groud_truth.csv，但它的格式和[tools](https://github.com/IPNL-POLYU/UrbanNavDataset/tree/master/tools/gt_vis)中的UrbanNav_TST_GT.txt并不相同，该如何转换以生成evo评估需要的ground truth呢？

期待您的回复！

**Comment by zhangluxiao** [comment]
你好，请问你是怎么解决这个问题的，如何获取这个真值做评估

**Comment by guojiabo** [comment]
同问
