### ISSUE TITLE
Time Difference between the observation files of smart phones(note8, pixel4) and Ground truth

### ISSUE THREAD

**Issue by faithyang** [IPNL-POLYU/UrbanNavDataset#54]
Hello, professors, the timestamp of obs data in observation files of note8 and pixel4 is like this "2021  5 17  2 33 13.4462116", but the timestamp of  ground truth is like this "1621218775000", so the time difference of these two phones is more than 0.4s, which makes insufficient accuracy. Do you have the ground truth of milliseconds level of these two phones, like p40pro and mi8.

note8 obs data:
![image](https://github.com/IPNL-POLYU/UrbanNavDataset/assets/6769656/3167a595-fc9b-4af9-8ad5-0e8aa263034e)

pixel4 obs data:
![image](https://github.com/IPNL-POLYU/UrbanNavDataset/assets/6769656/36e9ed84-57d2-4053-b5f3-928c2fb3931a)

ground truth:
![image](https://github.com/IPNL-POLYU/UrbanNavDataset/assets/6769656/c2dee017-1e2b-4d50-be64-9c13aa954326)

**Comment by DarrenWong** [comment]
You can use interpolation to have the GT for the timestamp between epochs or refer to the 100 hz ground truth 
[TST_100hz.txt](https://github.com/IPNL-POLYU/UrbanNavDataset/files/13931473/TST_100hz.txt) propagated by IMU using Novatel Inertial Explorer.
