### ISSUE TITLE
timestamp of SPAN-CPT in UrbanNav-HK-Data20200314 is not match with te image

### ISSUE THREAD

**Issue by Shujie-Hu** [IPNL-POLYU/UrbanNavDataset#55]
I extracted the images in the bag and the trajectory of SPAN-CPT with timestamp, but the motion state of the vehicle does not match the trajectory of SPAN-CPT.
![0cd85167e2d7b1e6d499c29014a7a569](https://github.com/IPNL-POLYU/UrbanNavDataset/assets/117510332/a6630924-892a-4695-b828-7fb7f0b0a51a)
SPAN-CPT trajectory show vehicle is turning at gpsWIS 549992.0
![20e825046fd76e1c8026d459358f071e](https://github.com/IPNL-POLYU/UrbanNavDataset/assets/117510332/cc5c4e57-c5e5-4dd6-ad0d-3d79e550b2e1)
but image show vehicle is turning at gpsWIS 550010
Could you please tell me why this problem occurs?

**Comment by DarrenWong** [comment]
Hello, can I know the UTC timestamp of the vehicle image? As the UTC and GPS time have 18 leaf seconds, it might possible have some problem when you compare the time directly. You can refer to this [page](https://github.com/IPNL-POLYU/UrbanNavDataset/blob/master/docs/GETTING_STARTED.md#time-synchronization-between-gps-time-and-ros-time) for the conversion.

**Comment by Shujie-Hu** [comment]
I have reconfirmed the code for extracting images from the bag, and I think that the timestamp of the image message header is UTC time and converted it to GPS time. Is there a problem with this process? I will take a screenshot of the code as follows:
![QQ图片20240120154007](https://github.com/IPNL-POLYU/UrbanNavDataset/assets/117510332/d03a0ec9-24ef-401b-9fe5-dedc131de272)
![QQ图片20240120154017](https://github.com/IPNL-POLYU/UrbanNavDataset/assets/117510332/99e5d1e3-c74e-4d23-94e5-072bae416de5)

**Comment by DarrenWong** [comment]
Hey Shujie, your code is correct. Seems the rosbag timestamp indeed has a gap with the GPS time as no hardware time sync was applied in the pilot data. Suggest you can use the data collected in 2021 or refer to the timestamp of rosbag topic  between `/novatel_data/inspvax` and `/camera/image_color/header` to adjust the time manual. 

The UTC stamp I tested was based on Matlab [function](https://github.com/IPNL-POLYU/UrbanNavDataset/blob/master/docs/GETTING_STARTED.md#time-synchronization-between-gps-time-and-ros-time) and https://www.labsat.co.uk/index.php/en/gps-time-calculator.
1584175590 (UTC)- > week: 2096, second: 550010 (GPS)   -> the rosbag is (549993) at the same time.

**Comment by Shujie-Hu** [comment]
> Hey Shujie, your code is correct. Seems the rosbag timestamp indeed has a gap with the GPS time as no hardware time sync was applied in the pilot data. Suggest you can use the data collected in 2021 or refer to the timestamp of rosbag topic between `/novatel_data/inspvax` and `/camera/image_color/header` to adjust the time manual.
> 
> The UTC stamp I tested was based on Matlab [function](https://github.com/IPNL-POLYU/UrbanNavDataset/blob/master/docs/GETTING_STARTED.md#time-synchronization-between-gps-time-and-ros-time) and https://www.labsat.co.uk/index.php/en/gps-time-calculator. 1584175590 (UTC)- > week: 2096, second: 550010 (GPS) -> the rosbag is (549993) at the same time.

Thanks for your response! I'll try again.
