### ISSUE TITLE
Aligning Point Cloud Map with Google Earth and Missing novatel_msgs

### ISSUE THREAD

**Issue by HowieHepburn** [IPNL-POLYU/UrbanNavDataset#58]
Firstly, I would like to express my gratitude for your outstanding work on the UrbanNav dataset. The resources and documentation provided have been incredibly helpful in our research.

We are currently working on aligning the point cloud map obtained from your dataset with Google Earth. However, we are facing some difficulties in this process. Could you kindly provide guidance or suggest any specific steps or tools that can help in achieving this alignment?
Additionally, we encountered an issue while attempting to compile our workspace. We consistently receive the following error message like this:
`Could not find the required component 'novatel_msgs'`
We have made several attempts to resolve this issue, including installing the following packages:
```
sudo apt install ros-noetic-novatel-oem7-driver
sudo apt install ros-noetic-novatel-gps-driver
sudo apt install ros-noetic-novatel-gps-msgs
```
Despite these efforts, the novatel_msgs package still cannot be found during the compilation process. Could you please provide any insights or suggestions on how to resolve this issue?

Thank you very much for your time and assistance. We greatly appreciate any help you can offer.

**Comment by DarrenWong** [comment]
It might have some problem in the dependence installation. Suggest you try in a clear environment. 

You can directly read the ground truth in text fromat in [here](https://github.com/IPNL-POLYU/UrbanNavDataset?tab=readme-ov-file#datasets),
![image](https://github.com/IPNL-POLYU/UrbanNavDataset/assets/5771106/c5bc2fe7-2395-4a1c-8b62-c3f416c6e900)

But if you want to align the point cloud map, might be you need to download the higher frequency ground truth. You can refer to this [link](https://github.com/IPNL-POLYU/UrbanNavDataset/issues/54#issuecomment-1890938592)
