### ISSUE TITLE
vins fusion not work well on HK deep urban

### ISSUE THREAD

**Issue by ouguangjun** [IPNL-POLYU/UrbanNavDataset#60]
When I ran the hk deep urban dataset with vins fusion, it didn't work very well, especially when the car stopped and started to float. Could you please provide your yaml file? Thank you. Here is my yaml.

hk_stereo_imu_config.yaml:

---------------------------------------------hk_stereo_imu_config.yaml:-------------------------------------------------------------
%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 2  

imu_topic: "/imu/data"
image0_topic: "/zed2/camera/left/image_raw"
image1_topic: "/zed2/camera/right/image_raw"
output_path: "~/output/"

cam0_calib: "cam0_pinhole.yaml"
cam1_calib: "cam1_pinhole.yaml"
image_width: 672
image_height: 376
   

#Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 9.9885234402635936e-01, 1.3591158885981787e-03,
       4.7876378696062108e-02, -8.4994249456545504e-02,
       -4.7864188349269129e-02, -7.9091258538426246e-03,
       9.9882253939420773e-01, 6.6169337079143220e-01,
       1.7361758877140372e-03, -9.9996779874765440e-01,
       -7.8349959194297103e-03, -3.0104266183335913e+00, 0., 0., 0., 1.]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [9.9872871452749812e-01, 1.5287637777597791e-03,
       5.0384696680271013e-02, 7.5332297629590136e-02,
       -5.0367177375936031e-02, -9.8967686259809895e-03,
       9.9868173179143760e-01, 6.8331281093016005e-01,
       2.0253941424080261e-03, -9.9994985716888607e-01,
       -9.8071874914416046e-03, -3.0079627649520204e+00, 0., 0., 0., 1.]

#Multiple thread support
multiple_thread: 4

#feature traker paprameters
max_cnt: 150           
min_dist: 30            
freq: 10               
F_threshold: 1.0        
show_track: 1        
flow_back: 1           
#optimization parameters
max_solver_time: 0.04  
max_num_iterations: 8  
keyframe_parallax: 10.0 

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 1.1197412605492375e-02          
gyr_n: 1.0270904839480961e-02             
acc_w: 1.1751767903346351e-04         
gyr_w: 9.1355383994881894e-05       
g_norm: 9.81007     

#unsynchronization parameters
estimate_td: 0                      
td: 0.0                            

#loop closure parameters
load_previous_pose_graph: 0      
pose_graph_save_path: "~/output/pose_graph/"
save_image: 1                   

---------------------------------------------cam0_pinhole.yaml-------------------------------------------------------------
model_type: PINHOLE
camera_name: camera
image_width: 672
image_height: 376
distortion_parameters:
   k1: -0.0442856
   k2: 0.0133574
   p1: 0
   p2: 0
projection_parameters:
   fx: 264.9425
   fy: 264.79
   cx: 334.3975
   cy: 183.162
---------------------------------------------cam1_pinhole.yaml:-------------------------------------------------------------
model_type: PINHOLE
camera_name: camera
image_width: 672
image_height: 376
distortion_parameters:
   k1: -0.0423469
   k2: 0.0115525
   p1: 0
   p2: 0
projection_parameters:
   fx: 264.2125
   fy: 264.155
   cx: 341.635
   cy: 183.993

**Comment by DarrenWong** [comment]
Can you try this [repo](https://github.com/baaixw/VINS-Fusion-for-UrbanNavDataset-Evaluation)?

**Comment by ouguangjun** [comment]
thanks！

Darren Wong ***@***.***>于2024年6月14日 周五22:05写道：
