### ISSUE TITLE
怎么在包里添加Sensor_msgs/NavSatFix话题?

### ISSUE THREAD

**Issue by HuL0713** [IPNL-POLYU/UrbanNavDataset#63]
您好，首先感谢你们的工作和开源，我想请教一下：我怎么样能像UrbanNav-HK-Data20190428数据包一样，给UrbanNav-HK-Medium-Urban-1数据包添加Sensor_msgs/NavSatFix消息呢，我想用LIOSAM跑一下这个数据包，但它需要卫星定位信息来初始化，期待您的回复

**Comment by DarrenWong** [comment]
你可以采用rosbag API来写入，https://blog.csdn.net/maizousidemao/article/details/136779867。 注意先存多一份原始的bag，写入bag如果不正确关闭可能会出错，需要reindex。
