### ISSUE TITLE
Sensor Height

### ISSUE THREAD

**Issue by haider8645** [IPNL-POLYU/UrbanNavDataset#66]
Hello!

could you please tell me the sensor height of the lidar during data collection? I found a picture (which was blurry) and I guessed that the height of the Velodyne HDL-32E is 1.832m?

Best regards,
Haider

**Comment by DarrenWong** [comment]
The height should be around 2.1 meters as measured by the LiDAR center. You can also pick up the ground points to check the actual values.

![image](https://github.com/user-attachments/assets/dd89fad1-ceb9-493c-9f9a-36bb38963744)
