### ISSUE TITLE
How to download the 3D PointCloud prior map?

### ISSUE THREAD

**Issue by maSiki29** [IPNL-POLYU/UrbanNavDataset#67]
Hello,

 I would like to download the point cloud map at the column named "3D PointCloud" in this section [https://github.com/IPNL-POLYU/UrbanNavDataset?tab=readme-ov-file#datasets](https://github.com/IPNL-POLYU/UrbanNavDataset?tab=readme-ov-file#datasets) 
 However, I couldn't find any valid download link on the website or this github repo. The Potree website only has some export buttons (as shown in the following image), but they don’t work. Is there any available way to download the point cloud map? Thanks!

<img width="297" alt="截圖 2024-08-23 下午5 22 34" src="https://github.com/user-attachments/assets/5682efec-85a4-4857-ae69-a151dfca6148">

**Comment by DarrenWong** [comment]
Thank you for your interest in our data. Please check the below link for the point cloud map for the UrbanNav dataset. You can downsample the point cloud if needed using the script inside the folder if needed.

https://www.dropbox.com/scl/fo/bpawd1lh4q6dnst70nz0x/h?rlkey=mlol5haclievtn7bj2y1r2xgc&dl=0

**Comment by maSiki29** [comment]
Thanks for the reply and your great work!

**Comment by DarrenWong** [comment]
Can I know the meaning of point cloud frame? The map data is saved as PCD files. You can read it and publish as any frame_id using ROS accourding Section4 in  http://wiki.ros.org/pcl_ros
![image](https://github.com/user-attachments/assets/dc228d0c-c267-412e-af40-362e8b525fcf)

**Comment by maSiki29** [comment]
I use the "point cloud frame" to describe the point cloud measurement by the lidar at the timestamp t. From my understanding, a stream of point cloud frame is saved in the ```/velodyne_points```. 
Each PointCloud2 message has frame_id to indicate the coordinate system at the timestamp. And my previous question is that if the point cloud map is obtained by transforming these point cloud frames to the map coordinate.

**Comment by maSiki29** [comment]
I explain why I want to check the map generation. I would like to use this dataset in a particle filter-based localization work.
In this work, the particle weight is updated by computing the similarity between the real-time point cloud frame at time t and the particle measurement under the map. 
Most of works obtain the high-definition (HD) prior map in advance, then collect the real-time point cloud and gt pose on the same road again. Finally, the work match the real-time measurement and map to do localization.

So I think it doesn't make sense if the map and real-time point cloud frame (in the ```/velodyne_points```) come from the same source.

**Comment by DarrenWong** [comment]
> I use the "point cloud frame" to describe the point cloud measurement by the lidar at the timestamp t. From my understanding, a stream of point cloud frame is saved in the `/velodyne_points`. Each PointCloud2 message has frame_id to indicate the coordinate system at the timestamp. And my previous question is that if the point cloud map is obtained by transforming these point cloud frames to the map coordinate.

Yes, the map is accumulated by the point cloud and the corresponding pose

**Comment by DarrenWong** [comment]
> I explain why I want to check the map generation. I would like to use this dataset in a particle filter-based localization work. In this work, the particle weight is updated by computing the similarity between the real-time point cloud frame at time t and the particle measurement under the map. Most of works obtain the high-definition (HD) prior map in advance, then collect the real-time point cloud and gt pose on the same road again. Finally, the work match the real-time measurement and HD map to do localization.
> 
> So I think it doesn't make sense if the map and real-time point cloud frame (in the `/velodyne_points`) come from the same source.

Thanks for your interest in our data. We do not provide a prior map in existing open-source data and the map provided is for visualization only. You can refer to some datasets that include a prior map such as new college which includes a prior map collected by survey grade BLK360 LiDAR scanner [https://ori-drs.github.io/newer-college-dataset/]

**Comment by maSiki29** [comment]
Thank you for the information!
