### ISSUE TITLE
Reference data convention

### ISSUE THREAD

**Issue by paaraujo** [IPNL-POLYU/UrbanNavDataset#7]
I am doing some experiments with the dataset and I need to compare my navigation solution to the reference. I have two questions regarding the txt file containing the reference data. Are the velocities expressed in the body frame? So, if I need the velocities in the ENU coordinate system like the GNSS data, I need to rotate them using the attitude angles. Is it a correct interpretation? Also, the last attitude angle is named "heading". Is it the yaw or the azimuth?

**Comment by DarrenWong** [comment]
Dear Paulo,

For Q1, yes, the velocities are expressed in the body frame. For the velocities in the ENU, you can check out the Novatel official  documents  at [Relating the Body Frame to the Local Level Frame](https://hexagondownloads.blob.core.windows.net/public/Novatel/assets/Documents/Bulletins/apn037/apn037.pdf)

The attitude angle is Azimuth, you can also refer to the tools [here](https://github.com/IPNL-POLYU/UrbanNavDataset/tree/master/tools/gt_vis) for visualizing and understanding the GT in ENU frame or body frame.

**Comment by paaraujo** [comment]
Thank you very much @DarrenWong, I will check those documents.
