### ISSUE TITLE
3D Point Cloud Map Availability

### ISSUE THREAD

**Issue by Mahmoudadham4040** [IPNL-POLYU/UrbanNavDataset#70]
Hello, I would like to ask if the 3D point cloud map is available for download?

**Comment by DarrenWong** [comment]
Thank you for your interest in our work. You can access the point cloud map for the UrbanNav dataset using the link below. You can downsample the point cloud if needed using the script inside the folder if needed. 

https://www.dropbox.com/scl/fo/bpawd1lh4q6dnst70nz0x/h?rlkey=mlol5haclievtn7bj2y1r2xgc&dl=0

Please note that the point cloud map is accumulated from the point cloud and its ground truth data. We have not further processed the point cloud map at this stage.
