### ISSUE TITLE
Experimental results of 3DMA on the urbannav dataset in the paper

### ISSUE THREAD

**Issue by MrTHMX** [IPNL-POLYU/UrbanNavDataset#71]
Hello, thanks for your work. I am comparing my work with your 3DMA recently. I would like to ask if you can provide the positioning results of each epoch of 3DMA on f9p for trajectory evaluation, etc. Thank you very much!
![image](https://github.com/user-attachments/assets/f78577c0-c96a-452a-bdd4-75bf3a94a9c8)

**Comment by ivannhf** [comment]
Thank you for your interest in our dataset. Here's the link to access the position results:
https://www.dropbox.com/scl/fo/5tbmc2xeubjaae8sjkqtw/AAU7LpBsWx8T_3KzzfVCfik?rlkey=ek7suym6efk21p1hm9pk20qys&st=qf6jug50&dl=0

**Comment by MrTHMX** [comment]
Thank you very much！
