### ISSUE TITLE
imu方向问题

### ISSUE THREAD

**Issue by snowflakezzz** [IPNL-POLYU/UrbanNavDataset#72]
老师您好，最近使用UrbanNav-HK-Medium-Urban-1数据集的时候发现ros包中imu数据加计的z轴输出为正，和图片标注的imu轴向不符，请问imu的轴向是什么呢？
![Screenshot from 2024-12-02 16-26-54](https://github.com/user-attachments/assets/4cf440c8-3f07-4e77-8488-d3e58a30bba3)

**Comment by DarrenWong** [comment]
你好，imu测得是加速度，例如静止时候z轴朝上加速度为0m/s^2，这时候有重力朝下速度-9.8m/s^2， 0- (-9.8)=9.8 m/s^2. 如果z轴朝下，这时候重力跟轴方向一致，就应该是  0- (9.8)=-9.8 m/s^2.

**Comment by snowflakezzz** [comment]
（自动回复）邮件已收到~

**Comment by snowflakezzz** [comment]
明白了，感谢老师回复
