### ISSUE TITLE
Time information of UrbanNav-HK-Data20190428 and UrbanNav-HK-Data20200314 in RINEX

### ISSUE THREAD

**Issue by tipf** [IPNL-POLYU/UrbanNavDataset#9]
Dear authors,
I got a bit of trouble with the timestamps of both datasets UrbanNav-HK-Data2019 and UrbanNav-HK-Data2020.
According to the table and the IMU/GT files,  they have a duration of 8 respectively 5 minutes.
The RINEX files, however, are 29 and 44 minutes long and the periods do not overlap fully.

Could you help me with that issue?

Best Regards
Tim

**Comment by DarrenWong** [comment]
Dear Tim

Please refer to the duration of the IMU/GT files as we do not cut the RINEX within the duration in these two pilot data. You can use rtkconvert in RTKLIB to preprocess the RINEX files.

You can also check out the data collected in 2021, the RINEX files are well aligned with the IMU/GT.

Best Regards,
Darren
